Content:
    - modules/doc/content
    - framework/doc/content
    - modules/chemical_reactions/doc/content
    - modules/combined/doc/content
    - modules/contact/doc/content
    - modules/external_petsc_solver/doc/content
    - modules/geochemistry/doc/content
    - modules/fluid_properties/doc/content
    - modules/fsi/doc/content
    - modules/functional_expansion_tools/doc/content
    - modules/heat_conduction/doc/content
    - modules/level_set/doc/content
    - modules/misc/doc/content
    - modules/navier_stokes/doc/content
    - modules/peridynamics/doc/content
    - modules/phase_field/doc/content
    - modules/porous_flow/doc/content
    - modules/ray_tracing/doc/content
    - modules/rdg/doc/content
    - modules/reactor/doc/content
    - modules/richards/doc/content
    - modules/stochastic_tools/doc/content
    - modules/tensor_mechanics/doc/content
    - modules/thermal_hydraulics/doc/content
    - modules/xfem/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
    favicon: media/moose.ico
    google_analytics: True

Extensions:
    MooseDocs.extensions.navigation:
        name: 'MOOSE'
        repo: https://github.com/idaholab/moose
        google-cse: 000781241768298771085:pedtnlxdkx8
        menu:
            Getting Started: getting_started.menu.md
            Documentation: documentation.menu.md
            Help: help.menu.md
            Gallery: /gallery.md
            News: newsletter/index.md
            Citing: citing.md
    MooseDocs.extensions.bibtex:
        duplicates: !include modules/doc/duplicate_bibs.yml
    MooseDocs.extensions.katex:
        macros: !include modules/doc/katex_macros.yml
    MooseDocs.extensions.appsyntax: # WARNING: this must follow katex for doco pages to work
        executable: ${MOOSE_DIR}/modules/combined
        unregister:
            framework: !include framework/doc/unregister.yml
            thermal_hydraulics:
                AddComponentAction: Components/*/*
                Component: Components/*/*
        remove:
            framework: !include framework/doc/remove.yml
            richards: !include modules/richards/doc/remove.yml
            stochastic_tools: !include modules/stochastic_tools/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.content:
        source_links:
            action: source/actions/Action.md
            actions: source/actions/Action.md
            auxkernels: AuxKernels/index.md
            bcs: syntax/BCs/index.md
            constraints: syntax/Constraints/index.md
            controls: syntax/Controls/index.md
            dampers: syntax/Dampers/index.md
            dgkernels: syntax/DGKernels/index.md
            dirackernels: syntax/DiracKernels/index.md
            distributions: syntax/Distributions/index.md
            executioners: syntax/Executioner/index.md
            functions: syntax/Functions/index.md
            fvbcs: syntax/FVBCs/index.md
            fvkernels: syntax/FVKernels/index.md
            fviks: syntax/FVInterfaceKernels/index.md
            ics: syntax/ICs/index.md
            indicators: syntax/Adaptivity/Indicators/index.md
            interfacekernels: syntax/InterfaceKernels/index.md
            interfaces: framework_development/interfaces/index.md
            kernels: syntax/Kernels/index.md
            linesearches: syntax/LineSearches/index.md
            markers: syntax/Adaptivity/Markers/index.md
            materials: syntax/Materials/index.md
            mesh: syntax/Mesh/index.md
            meshgenerators: syntax/Mesh/index.md
            multiapps: syntax/MultiApps/index.md
            nodalkernels: syntax/NodalKernels/index.md
            outputs: syntax/Outputs/index.md
            parser: source/parser/Parser.md
            partitioner: syntax/Mesh/Partitioner/index.md
            postprocessors: syntax/Postprocessors/index.md
            preconditioners: syntax/Preconditioning/index.md
            predictors: syntax/Executioner/Predictor/index.md
            problems: syntax/Problem/index.md
            raybcs: syntax/RayBCs/index.md
            raykernels: syntax/RayKernels/index.md
            relationshipmanagers: source/relationshipmanagers/RelationshipManager.md
            reporters: syntax/Reporters/index.md
            restart: application_usage/restart_recover.md
            samplers: syntax/Samplers/index.md
            scalarkernels: syntax/ScalarKernels/index.md
            splits: syntax/Preconditioning/index.md
            surrogates: syntax/Surrogates/index.md
            timeintegrators: syntax/Executioner/TimeIntegrator/index.md
            timesteppers: syntax/Executioner/TimeStepper/index.md
            transfers: syntax/Transfers/index.md
            userobject: syntax/UserObjects/index.md
            userobjects: syntax/UserObjects/index.md
            utils: framework_development/utils/index.md
            variables: syntax/Variables/index.md
            vectorpostprocessors: syntax/VectorPostprocessors/index.md
    MooseDocs.extensions.civet:
        test_results_cache: '/tmp/civet/jobs'
        remotes:
            moose:
                url: https://civet.inl.gov
                repo: idaholab/moose
    MooseDocs.extensions.template:
        active: True
        args:
            company: Ford # used for example in python/MooseDocs/extensions/template.md
    MooseDocs.extensions.sqa:
        active: True
        reports: !include modules/doc/sqa_reports.yml
        categories:
            framework: !include framework/doc/sqa_framework.yml
            tensor_mechanics: !include modules/tensor_mechanics/doc/sqa_tensor_mechanics.yml
            stochastic_tools: !include modules/stochastic_tools/doc/sqa_stochastic_tools.yml
            contact: !include modules/contact/doc/sqa_contact.yml
            heat_conduction: !include modules/heat_conduction/doc/sqa_heat_conduction.yml
            fluid_properties: !include modules/fluid_properties/doc/sqa_fluid_properties.yml
            misc: !include modules/misc/doc/sqa_misc.yml
            phase_field: !include modules/phase_field/doc/sqa_phase_field.yml
            xfem: !include modules/xfem/doc/sqa_xfem.yml
            navier_stokes: !include modules/navier_stokes/doc/sqa_navier_stokes.yml
            rdg: !include modules/rdg/doc/sqa_rdg.yml
            reactor: !include modules/reactor/doc/sqa_reactor.yml
            ray_tracing: !include modules/ray_tracing/doc/sqa_ray_tracing.yml
            fsi: !include modules/fsi/doc/sqa_fsi.yml
            thermal_hydraulics: !include modules/thermal_hydraulics/doc/sqa_thermal_hydraulics.yml
            porous_flow: !include modules/porous_flow/doc/sqa_porous_flow.yml
            level_set: !include modules/level_set/doc/sqa_level_set.yml

        requirement-groups:
            dgkernels: DGKernel Objects
            interfacekernels: InterfaceKernel Objects

    MooseDocs.extensions.algorithm:
        active: True
