{% set build = 2 %}
{% set strbuild = "build_" + build|string %}
{% set version = "4.0.1" %}

package:
  name: moose-mpich
  version: {{ version }}

source:
  - path: .

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('moose-mpich', max_pin='x.x') }}

requirements:
  build:
    - {{ base_mpich }}
    - {{ base_mpicc }}
    - {{ base_mpicxx }}
    - {{ base_mpifort }}
    - {{ moose_hdf5 }}
    - {{ moose_ld64 }}          # [osx]
    - autoconf                  # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - make                      # [unix]
    - gnuconfig                 # [arm64]
  host: []
  run:
    - {{ base_mpich }}
    - {{ base_mpicc }}
    - {{ base_mpicxx }}
    - {{ base_mpifort }}
    - {{ moose_hdf5 }}
    - {{ moose_ld64 }}          # [osx]
    - autoconf                  # [osx]
    - automake                  # [osx]
    - libtool                   # [osx]
    - make                      # [osx]
    - openssl <3
    - setuptools <60
    - mpi 1.0 mpich
test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate_moose-mpich.sh

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'A top-level package designed to control environment variables related to conda-forge provided MPICH'
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: http://www.mpich.org/documentation/guides
  dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page

extra:
  recipe-maintainers:
    - milljm
