# Do not use jinja templating (A physical change to this file is required to trigger a build)
{% set build = 3 %}
{% set strbuild = "build_" + build|string %}
{% set version = "3.16.5" %}
{% set sha256 = "d676eb67e79314d6cca6422d7c477d2b192c830b89d5edc6b46934f7453bcfc0" %}

package:
  name: moose-petsc
  version: {{ version }}

source:
  - path: ../../petsc
  - path: ../../scripts/configure_petsc.sh
  - patches:
      - no-cppflags-in-pkgconfig-cflags.patch

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('moose-petsc', max_pin='x.x')}}

requirements:
  build:
    - {{ moose_mpich }}
    - pkg-config

  host:
    - cmake
    - {{ moose_mpich }}

  run:
    - cmake
    - {{ moose_mpich }}

test:
  requires:
    - pkg-config
    - {{ moose_mpich }}

  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://petsc.org
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - milljm
