# Do not use jinja templating (A physical change to this file is required to trigger a build)
{% set build = 7 %}
{% set vtk_version = "9.1.0" %}
{% set friendly_version = "9.1" %}
{% set sha256 = "8fed42f4f8f1eb8083107b68eaa9ad71da07110161a3116ad807f43e5ca5ce96" %}

package:
  name: moose-libmesh-vtk
  version: {{ vtk_version }}

source:
  url: https://www.vtk.org/files/release/{{ friendly_version }}/VTK-{{ vtk_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS

requirements:
  build:
    - {{ moose_mpich }}
    - {{ moose_python }}
    - {{ moose_pyqt }}         # [not arm64]
    - cmake
    - ninja
    - {{ moose_libglu }}       # [linux]
    - {{ moose_mesalib }}      # [linux]
    - {{ moose_libxt }}        # [linux]
    - {{ moose_libsm }}        # [linux]
    - {{ moose_libx11 }}       # [linux]
    - {{ moose_libice }}       # [linux]
    - {{ moose_libxext }}      # [linux]
    - {{ moose_mesa_libgl }}   # [linux]
    - {{ moose_xorg_x11 }}     # [linux]

  run:
    - {{ moose_mpich }}
    - {{ moose_python }}
    - {{ moose_pyqt }}         # [not arm64]
    - {{ moose_libglu }}       # [linux]
    - {{ moose_mesalib }}      # [linux]
    - {{ moose_libxt }}        # [linux]
    - {{ moose_libsm }}        # [linux]
    - {{ moose_libx11 }}       # [linux]
    - {{ moose_libice }}       # [linux]
    - {{ moose_libxext }}      # [linux]
    - {{ moose_mesa_libgl }}   # [linux]
    - {{ moose_xorg_x11 }}     # [linux]

test:
  commands:
    - test -f $PREFIX/libmesh-vtk/lib/libvtkCommonCore-{{ friendly_version }}.dylib # [osx]
    - test -f $PREFIX/libmesh-vtk/lib/libvtkCommonCore-{{ friendly_version }}.so    # [linux]
  imports:
    - PyQt5  # [not arm64]
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - milljm
